project_id = "uxhcsjlfwkhwkvhfacho"

# Configuração global para usar apenas regiões autorizadas pela Binance e OKX
[functions]
# Executar funções apenas em regiões com acesso permitido (US-East geralmente permitido)
region = "us-east-1"

[functions.auto-arbitrage-bot]
verify_jwt = false

[functions.auto-transfer-crypto]
verify_jwt = false

[functions.mexc-api]
verify_jwt = false

[functions.test-binance-connection]
verify_jwt = false

[functions.okx-api]
verify_jwt = false

[functions.binance-market-data]
verify_jwt = false

[functions.get-portfolio]
verify_jwt = false

[functions.hft-websocket-engine]
verify_jwt = false

[functions.triangular-arbitrage-ws]
verify_jwt = false

[functions.binance-withdrawal]
verify_jwt = false

[functions.okx-withdrawal]
verify_jwt = false

[functions.okx-internal-transfer]
verify_jwt = false

[functions.binance-convert-to-usdt]
verify_jwt = false

[functions.binance-swap-token]
verify_jwt = false

[functions.okx-swap-token]
verify_jwt = false

[functions.binance-all-balances]
verify_jwt = false

[functions.okx-convert-to-usdt]
verify_jwt = false

[functions.execute-cross-exchange-arbitrage]
verify_jwt = false

[functions.detect-arbitrage-opportunities]
verify_jwt = false

[functions.market-trends-analyzer]
verify_jwt = false

[functions.bright-data-proxy]
verify_jwt = false
