project_id = "uxhcsjlfwkhwkvhfacho"

# Configuração global para usar apenas regiões autorizadas pela Binance e OKX
[functions]
# Executar funções apenas em regiões com acesso permitido (US-East geralmente permitido)
region = "us-east-1"

[functions.auto-arbitrage-bot]
verify_jwt = false

[functions.auto-transfer-crypto]
verify_jwt = false

[functions.mexc-api]
verify_jwt = false